mainFileName: processedGenshinDatamine #main name of the directory containing of all the extracted files
parentDir: [ #even the "parentDir" and "childFileNames" can be changed
    "weapon", #if changing these change the dictionary keys below too
    "character",
    "talent", 
    "artifact",
    "enemy"
    ]
childFileNames: #child file names 
    weapon: [
        "WeaponExcelConfigData",
        "WeaponCurveExcelConfigData",
        "WeaponPromoteExcelConfigData",
        
        "EquipAffixExcelConfigData" #weapons effects (arti set bonuses too)
        ]
    character: [
        "AvatarExcelConfigData", #base stats
        "AvatarCurveExcelConfigData",
        "AvatarPromoteExcelConfigData",
         
        "AvatarCodexExcelConfigData" #release dates to determine released characters
        ]
    talent: [
        "AvatarSkillExcelConfigData", #talents
        "AvatarSkillDepotExcelConfigData", #ascension talents
        "ProudSkillExcelConfigData", #talent multipliers
        "AvatarTalentExcelConfigData" #constellations
        ]
    artifact: [
        "ReliquaryLevelExcelConfigData", #mainstats
        "ReliquaryAffixExcelConfigData" #substats
        ]
    enemy: [
        "MonsterExcelConfigData", #mob list
        "MonsterCurveExcelConfigData", #mob base stat scaling
        ]
languageFiles:  #the ones not commented out will remain
    TextCHS.json: True #Chinese Simplified
    TextCHT.json: False #Chinese Traditional
    TextDE.json: True #German
    TextEN.json: True #English
    TextES.json: False #Spanish
    TextFR.json: False #French
    TextID.json: False #Indonesian
    TextJA.json: True #Japanese
    TextKO.json: False #Korean
    TextPT.json: False #Portuguese
    TextRU.json: False #Russian
    TextTH.json: False #Thai
    TextVI.json: False #Vietnamese
    
...