mainFileName: processedGenshinDatamine #main name of the directory containing of all the extracted files
parentDir: [ 
    "weapon",
    "character",
#    "talent",
#    "artifact",
#    "enemy"
    ]
childDir: #child directory names
    weapon: [
        "weaponBaseStats",
        "weaponGrowthCurves",
        "weaponAscensionBonus"
        ]
    character: [
        "characterBaseStats",
        "characterGrowthCurves",
        "characterAscensionBonus",
        ]
childFileNames: #child file names
    weapon: [
        "WeaponExcelConfigData",
        "WeaponCurveExcelConfigData",
        "WeaponPromoteExcelConfigData"
        ]
    character: [
        "AvatarExcelConfigData",
        "AvatarCurveExcelConfigData",
        "AvatarPromoteExcelConfigData"
        ]
...