mainFileName: processedGenshinDatamine #main name of the directory containing of all the extracted files
parentDir: [ #even the "parentDir" and "childFileNames" can be changed
    "weapon",
    "character",
#    "talent", 
#    "artifact",
#    "enemy"
    ]
childFileNames: #child file names 
    weapon: [
        "WeaponExcelConfigData",
        "WeaponCurveExcelConfigData",
        "WeaponPromoteExcelConfigData"
        ]
    character: [
        "AvatarExcelConfigData",
        "AvatarCurveExcelConfigData",
        "AvatarPromoteExcelConfigData"
        ]
...